---
title: "Problemas 1"
author: "George G. Vega Yon"
date: "December 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Donde esta el caracol?

El siguiente ejemplo es del paquete [profvis](https://rstudio.github.io/profvis/examples.html#example-1)

```{r}
# Cargando el paquete
library(profvis)

# Generate data
times <- 1e5
cols <- 150
data <- as.data.frame(x = matrix(rnorm(times * cols, mean = 5), ncol = cols))
data <- cbind(id = paste0("g", seq_len(times)), data)

profvis({
  data1 <- data   # Store in another variable for this run

  # Get column means
  means <- apply(data1[, names(data1) != "id"], 2, mean)

  # Subtract mean from each column
  for (i in seq_along(means)) {
    data1[, names(data1) != "id"][, i] <- data1[, names(data1) != "id"][, i] - means[i]
  }
})


profvis({
  data1 <- data   # Store in another variable for this run

  # Get column means
  means <- colMeans(data1[, names(data1) != "id"])

  # Subtract mean from each column
  data1[,names(data1) != "id"] <- data1[,names(data1) != "id"] -
    matrix(means, nrow = nrow(data1), ncol = ncol(data1) - 1, byrow = TRUE)
  # for (i in seq_along(means)) {
  #   data1[, names(data1) != "id"][, i] <- data1[, names(data1) != "id"][, i] - means[i]
  # }
})
```


## Lapply

```{r}
mylapply <- function(X, FUN, ...) {
  
  # ans <- vector("list", length(X))
  
  FUN. <- if (length(list(...))) function(x) FUN(x,...) 
  else FUN
    
  is  <- seq_along(X)
  ans <- list()
  for (i in is)
    ans[[i]] <- FUN.(X[[i]])
  
  ans
  
}

fun <- function(x) {
  
  mean(sqrt(abs(rnorm(100))))
  
}

microbenchmark::microbenchmark(
  lapply   = lapply(1:1e4, fun),
  mylapply = mylapply(1:1e4, fun), times = 10L
)
```

